### ISSUE TITLE
Flip Creating Issue In Iphone after generating ipa

### ISSUE THREAD

**Issue by chughashish47** [darenju/react-flip-page#92]
**How to reproduce**

Create a project from scratch using create-react-app:

npx create-react-app reproducing-issue
cd reproducing-issue
Install you dependency from npm:

npm i -P react-flip-page
And, inside src/App.js, change the content to be:

import React, { Component } from 'react';
import FlipPage from 'react-flip-page';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
        <FlipPage>
          <article>
            <h1>My awesome first article</h1>
            <p>My awesome first content</p>
          </article>
          <article>
            <h1>My wonderful second article</h1>
            <p>My wonderful second content</p>
          </article>
          <article>
            <h1>My excellent third article</h1>
            <p>My excellent third content</p>
          </article>
        </FlipPage>
      </div>
    );
  }
}

export default App;
Now, run the application with:

npm start
And try to navigate to next page slowly...and dont leave it shows previous page and when you leave then current page shows.

Stucked with it please help

**Comment by darenju** [comment]
Hello,

This problem has already been reported by someone directly to me via email. I have faced the same issue, but don’t have any problem running the package from a basic webpack setup. As you can see on [the demo page](http://darenju.me/react-flip-page/examples), the package is working correctly, with the latest version installed.

The issue doesn’t come from `react-flip-page`, but I must admit the problem is annoying. If someone would like to help solve this issue, I’d gladly accept the help.
